context:
  version: 1.2.0

package:
  name: markdown-toc
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/markdown-toc/-/markdown-toc-${{ version }}.tgz
  sha256: 4a5bf3efafb21217889ab240caacd795a1101bfbe07cd8abb228cc44937acd9c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script: |
      markdown-toc --help 2>&1 | grep -q 'Usage: markdown-toc \[options\] <input>'

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: API and CLI for generating a markdown TOC (table of contents) for a README or any markdown files.
  homepage: https://github.com/jonschlinkert/markdown-toc
  repository: https://github.com/jonschlinkert/markdown-toc

extra:
  recipe-maintainers:
    - danielnachun
